swagger: "2.0"
info:
  title: Test API
  description: This is a test API
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    get:
      summary: A test
      operationId: GetTest
      responses:
        '200':
          description: The test is successful

