-- nvim-treesitter main branch: no configs.setup() — vim.treesitter handles
-- highlighting automatically via the installed parsers.
-- Install / update parsers manually with :TSInstall <lang> or :TSUpdate.
-- Note: the main branch requires tree-sitter-cli for compilation:
--   brew install tree-sitter
